services:
  app:
    image: node:22-alpine
    container_name: kueli-app
    working_dir: /workspace/app
    # command: sh -c "npm install && npx prisma generate && npx prisma db push && npm run dev"
    command: tail -f /dev/null
    ports:
      - "3001:3000"
    volumes:
      - .:/workspace
      - ./data/uploads:/workspace/app/public/uploads
      - ./data/prisma:/workspace/app/prisma/db
      - /workspace/app/node_modules
      - /workspace/app/.next
    environment:
      - TZ=Asia/Tokyo
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    tty: true
    stdin_open: true
    restart: unless-stopped