root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/kueli-api ./cmd/kueli-api"
bin = "tmp/kueli-api"
full_bin = "tmp/kueli-api"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true
