FROM golang:1.22 AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/kueli-api ./cmd/kueli-api
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/kueli-admin ./cmd/kueli-admin

FROM gcr.io/distroless/base-debian12

WORKDIR /
COPY --from=build /out/kueli-api /kueli-api
COPY --from=build /out/kueli-admin /kueli-admin

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/kueli-api"]
